server:
  port: 9080

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/spring?createDatabaseIfNotExist=true
  username: root
  password: rootpass
  initialization-mode: ALWAYS
  
spring.jpa.hibernate.ddl-auto: none